<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8OruMXO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8OruMXO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8OruMXO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8OruMXO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8OruMXO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8OruMXO',
    'container.build_id' => '1e13f117',
    'container.build_time' => 1678737124,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8OruMXO');
